spring:
  application:
    name: tenpo
  datasource:
    url: jdbc:postgresql://localhost:5432/challenge
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

